import 'package:get/get.dart';

class MyLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar': {
          //auth
          'Email': 'الايميل',
          'Enter your email': 'ادخل الايميل',
          'Password': 'كلمة السر',
          'Enter your password': 'ادخل كلمة السر',
          'Login': 'تسجيل الدخول',

          //comments
          'Comments': 'التعليقات',
          'Write a comment ..': '.. اكتب تعليقاً',
          'comments' : 'من التعليقات',
          
          
          //home
          'Home Work': 'الواجبات',
          'Home': 'الرئيسية',

          //posts
          'Add Post': 'اضافة تغطية يومية',
          'Text': 'النص',
          'Enter text of post': 'ادخل نص المنشور',
          'Class': 'الصف',
          'Choose class': 'اختر الصف',
          'Images/Added videos': 'الصور/الفيديوهات المرفقة',
          'Images' : 'الصور',
          'Add image/video': 'اضف صورة/فيديو',
          'Add image' : 'اضافة صورة',
          'Post': 'نشر',
          'Posts': 'التغطيات اليومية',
          'Teacher': 'المعلم',
          'Likes': 'من الاعجابات',
          'Kj class coverage': 'تغطية صف الروضة',
          'First class coverage': 'تغطية الصف الاول',
          'before': 'قبل',
          'min': 'دقائق',
          'Error': 'خطأ',
          "You don't choose an image.": 'لم تقم باختيار صورة',
          'Search' : 'ابحث',

          //students
          'Students': 'الطلاب',
          'Late': 'متأخر',
          'Execuse': 'مستأذن',
          'Asbent': 'غائب',
          'Existing': 'موجود',
          'Prepare Tajweed Subject': 'تحضير مادة التجويد',
          'Prepare Memorizing subject': 'تحضير مادة الحفظ',
          'Student Attendance' : 'تحضير الطلاب',

          //teacher
          'Add Activity': 'اضافة نشاط',
          'Activity name': 'اسم النشاط',
          'Enter activity name': 'ادخل اسم النشاط',
          'Activity details': 'تفاصيل النشاط',
          'Enter Activity details': 'ادخل تفاصيل النشاط',
          'Activity date': 'تاريخ النشاط',
          'Enter Activity date': 'ادخل تاريخ النشاط',
          'Add': 'اضافة',
          'Add HomeWork': 'اضافة واجب',
          'HomeWork title': 'عنوان الواجب',
          'Enter homeWork title': 'ادخل عنوان الواجب',
          'Title' : 'العنوان',
          'HomeWork details': 'تفاصيل الواجب',
          'Enter homeWork details': 'ادخل تفاصيل الواجب',
          'Submission date': 'تاريخ التسليم',
          'Enter submission date': 'ادخل تاريخ التسليم',
          'Activity': 'النشاطات',
          //'Week plane': 'الخطة الاسبوعية',
          'Delete': 'حذف',
          'Edit': 'تعديل',
          'Camera': 'الكاميرا',
          'Gallery': 'المعرض',
          'Chats': 'المحادثات',
          'Type your message ..': '.. اكتب رسالتك',
          'Add lesson': 'اضافة درس',
          'Choose subject': 'اختر المادة',
          'Lesson name': 'اسم الدرس',
          'Enter lesson name': 'ادخل عنوان الدرس',
          'Lesson details': 'ادخل تفاصيل الدرس',
          'Enter lesson details': 'ادخل تفاصيل الدرس',
          'Lesson date': 'تاريخ الدرس',
          'Enter lesson date': 'ادخل تاريخ الدرس',
          'Add honor board': 'اضافة لوحة شرف',
          'Honor board' : 'لوحة الشرف',
          'Honor board name': 'عنوان لوحة الشرف',
          'Enter honor board name': 'ادخل عنوان لوحة الشرف',
          'Choose student': 'اختر الطالب',
          'Update honor board': 'تعديل لوحة الشرف',
          'Update': 'تعديل',
          'Tajweed Subject': 'مادة التجويد',
          'Memorizing Subject': 'مادة الحفظ',
          'Tajweed Subject HomeWork': 'واجب مادة التجويد',
          'Memorizing Subject HomeWork': 'واجب مادةالحفظ',
          'Teachers': 'المعلمين',
          'Share app': 'مشاركة التطبيق',
          'Contact Us': 'تواصل معنا',
          'About Us': 'حول التطبيق',
          'Settings': 'الاعدادات',
          'Log Out': 'تسجيل الخروج',
          'Choose division' : 'اختر الشعبة',
          'No students today' : 'لا يوجد طلاب',
          'No subjects' : 'لا يوجد مواد',
          'Update Post' : 'تعديل المنشور',
          'Class table' : 'جدول الحصص', 
          'Daily Coverage' : 'التغطية اليومية',
          'Week plane' : 'الخطة الاسبوعية',
          'Continuous Rating' : 'التقييم المستمر',
           'Honor board for' : 'لوحة شرف',
           'Add student' : 'اضف طالب',
           'Choose section' : 'اختر الشعبة',
           'Please select a section' : 'الرجاء اختيار شعبة',
           'Update lesson' : 'تعديل الدرس',
          //Super Visor
          'Subject': 'المادة',
          'SuperVisors': 'المشرفين',
          'Add Advertisement' : 'اضافة اعلان',
          'Enter title of advertisement' : 'ادخل عنوان الاعلان',
          'Enter text of advertisement' : 'ادخل نص الاعلان',
          'Advertisements' : 'الاعلانات',
          'Advertisement' : 'اعلان',
          'News' : 'الاخبار',
          'My advertisements' : 'اعلاناتي',
          'Type' : 'النوع',
          'Update Advertisement' : 'تعديل الاعلان',

          //parent
          "Number of attendance's days": 'عدد أيام الحضور',
          "Number of absence's days": 'عدد أيام الغياب',
          'Message parent': 'مراسلة ولي الامر',
          'Son Achievement': 'انجاز الابن',
          'My sons': 'ابنائي',
          'Parents': 'الاهل',
          'Parent honor board' : 'لوحة شرف اولياء الامور',
        },
        'en': {
          //auth
          'Email': 'Email',
          'Enter your email': 'Enter your email',
          'Password': 'Password',
          'Enter your password': 'Enter your password',
          'Login': 'Login',

          //comments
          'Comments': 'Comments',
          'Write a comment ..': 'Write a comment ..',
          'comments' : 'comments',

          //home
          'Home Work': 'Home Work',
          'Home': 'Home',

          //posts
          'Add Post': 'Add Post',
          'Text': 'Text',
          'Enter text of post': 'Enter text of post',
          'Class': 'Class',
          'Choose class': 'Choose class',
          'Images/Added videos': 'Images/Added videos',
          'Images' : 'Images',
          'Add image/video': 'Add image/video',
          'Add image' : 'Add image',
          'Post': 'Post',
          'Posts': 'Posts',
          'Teacher': 'Teacher',
          'Likes': 'Likes',
          'Kj class coverage': 'Kj class coverage',
          'First class coverage': 'First class coverage',
          'before': 'before',
          'min': 'min',
          'Error': 'Error',
          "You don't choose an image.": "You don't choose an image.",
          'Search' : 'Search',

          //students
          'Students': 'Students',
          'Late': 'Late',
          'Execuse': 'Execuse',
          'Asbent': 'Asbent',
          'Existing': 'Existing',
          'Prepare Tajweed Subject': 'Prepare Tajweed Subject',
          'Prepare Memorizing subject': 'Prepare Memorizing subject',
          'Student Attendance' : 'Student Attendance',

          //teacher
          'Add Activity': 'Add Activity',
          'Activity name': 'Activity name',
          'Enter activity name': 'Enter activity name',
          'Activity details': 'Activity details',
          'Enter Activity details': 'Enter Activity details',
          'Activity date': 'Activity date',
          'Enter Activity date': 'Enter Activity date',
          'Add': 'Add',
          'Add HomeWork': 'Add HomeWork',
          'HomeWork title': 'HomeWork title',
          'Enter homeWork title': 'Enter homeWork title',
          'Title' : 'Title',
          'HomeWork details': 'HomeWork details',
          'Enter homeWork details': 'Enter homeWork details',
          'Submission date': 'Submission date',
          'Enter submission date': 'Enter submission date',
          'Activity': 'Activity',
          'Week plane': 'Week plan',
          'Delete': 'Delete',
          'Edit': 'Edit',
          'Camera': 'Camera',
          'Gallery': 'Gallery',
          'Chats': 'Chats',
          'Type your message ..': 'Type your message ..',
          'Add lesson': 'Add lesson',
          'Choose subject': 'Choose subject',
          'Lesson name': 'Lesson name',
          'Enter lesson name': 'Enter lesson name',
          'Lesson details': 'Lesson details',
          'Enter lesson details': 'Enter lesson details',
          'Lesson date': 'Lesson date',
          'Enter lesson date': 'Enter lesson date',
          'Add honor board': 'Add honor board',
          'Honor board' : 'Honor board',
          'Honor board name': 'Honor board name',
          'Enter honor board name': 'Enter honor board name',
          'Choose student': 'Choose student',
          'Update honor board': 'Update honor board',
          'Update': 'Update',
          'Tajweed Subject': 'Tajweed Subject',
          'Memorizing Subject': 'Memorizing Subject',
          'Tajweed Subject HomeWork': 'Tajweed Subject HomeWork',
          'Memorizing Subject HomeWork': 'Memorizing Subject HomeWork',
          'Teachers': 'Teachers',
          'Share app': 'Share app',
          'Contact Us': 'Contact Us',
          'About Us': 'About Us',
          'Settings': 'Settings',
          'Log Out': 'Log Out',
          'Choose division' : 'Choose division',
          'No students today' : 'No students today',
          'No subjects' : 'No subjects',
          'Update Post' : 'Update Post',
          'Class table' : 'Class Table', 
          'Daily Coverage' : 'Daily Coverage',
          //'week Plane' : 'ًWeek Plane',
          'Continuous Rating' : 'Continuous Rating',
          'Honor board for' : 'Honor board for',
          'Add student' : 'Add student',
          'Choose section' : 'Choose section',
          'Please select a section': 'Please select a section',
          'Update lesson' : 'Update lesson',
          
          //Super Visor
          'Subject': 'Subject',
          'SuperVisors': 'SuperVisors',
          'Add Advertisement' : 'Add Advertisement',
          'Enter title of advertisement' : 'Enter title of advertisement',
          'Enter text of advertisement' : 'Enter text of advertisement',
          'Advertisements' : 'Advertisements',
          'Advertisement' : 'Advertisement',
          'News' : 'News',
          'My advertisements' : 'My advertisements',
          'Type' : 'Type',
          'Update Advertisement' : 'Update Advertisement',

          //parent
          "Number of attendance's days": "Number of attendance's days",
          "Number of absence's days": "Number of absence's days",
          "Message parent": 'Message parent',
          'Son Achievement': 'Son Achievement',
          'My sons': 'My sons',
          'Parents': 'Parent',
          'Parent honor board' : 'Parent honor board',

        },
      };
}
